---
- name: Prepare for Kalypso node
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/{{ env }}.yml

  tasks:
    - name: Include prepare role
      ansible.builtin.include_role:
        name: prepare
