---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    symbiotic:
      hosts:
        kalypso.symbitoic.mainnet.encapsulate.xyz:
          type: kalypso
