---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    symbiotic:
      hosts:
        kalypso.symbitoic.testnet.encapsulate.xyz:
          type: kalypso
