---
- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: "1777"

- name: Clone the repository to /tmp
  ansible.builtin.git:
    repo: "{{ symbiotic.kalypso.source_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    version: "{{ symbiotic.kalypso.version }}"
    force: true

- name: Build binary
  ansible.builtin.shell: rustup run {{ symbiotic.kalypso.rust.version }} cargo build --release
  args:
    chdir: "{{ tmp_dir }}/{{ project }}"
    executable: /bin/bash
    creates: "{{ tmp_dir }}/{{ project }}/{{ kalypso_service_default_binary_name }}"
  environment:
    PATH: "{{ rust.path }}/bin:{{ ansible_env.HOME }}/.risc0/bin:{{ ansible_env.PATH }}"
  when: mode == "cpu"

- name: Build binary to support gpu
  ansible.builtin.shell: rustup run {{ symbiotic.kalypso.rust.version }} cargo build --release --features gpu
  args:
    chdir: "{{ tmp_dir }}/{{ project }}"
    executable: /bin/bash
    creates: "{{ tmp_dir }}/{{ project }}/target/release/{{ kalypso_service_default_binary_name }}"
  environment:
    PATH: "{{ rust.path }}/bin:{{ ansible_env.HOME }}/.risc0/bin:/usr/local/cuda/bin:{{ ansible_env.PATH }}"
  when: mode == "gpu"

- name: Copy the built binaries to the target directory
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/target/release/{{ item.src }}"
    dest: "{{ kalypso_bin_dir }}/{{ item.dest }}"
    mode: "0755"
    owner: root
    group: root
    remote_src: true
  with_items:
    - { src: "host", dest: "test-connection" }
    - { src: "benchmark", dest: "benchmark" }
    - { src: "{{ kalypso_service_default_binary_name }}", dest: "{{ service_identifier }}" }
  notify:
    - Restart service

- name: Clean up the temporary repository directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent

- name: Clean rzup
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.risc0"
    state: absent

- name: Remove rzup PATH addition
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: '^export PATH="\$PATH:/root/.risc0/bin"$'
    state: absent
